name: chameleonultragui
description: Enhanced cross-platform GUI for Chameleon Ultra with Proxmark3-style features.
publish_to: "none"

version: 2.0.0+0

environment:
  sdk: ">3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:
  async:

  flutter_libserialport:
    git:
      url: https://github.com/ChameleonUltraGUI/flutter_libserialport.git
      ref: main
  provider: ^6.0.5
  logger: ^2.0.1
  convert: ^3.1.1
  shared_preferences: ^2.2.1
  ffigen: ^19.0.0
  dylib: ^0.3.3
  ffi: ^2.1.0
  usb_serial:
    git:
      url: https://github.com/ChameleonUltraGUI/usbserial.git
      ref: fix-usbserial
  file_saver:
    git:
      url: https://github.com/ChameleonUltraGUI/file_saver.git
      ref: fix-windows
  file_picker: ^10.2.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.0.0
  http: ^1.1.0
  archive: ^4.0.1
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^12.0.0+1
  protobuf: ^2.1.0
  collection: ^1.17.1
  crypto: ^3.0.3
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.1.13
  flutter_localizations:
    sdk: flutter
  intl: any
  wakelock_plus: ^1.2.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

  # Enhanced features for Proxmark3 compatibility
  flutter_syntax_view: ^4.0.0
  xterm: ^3.4.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "assets/background-color.png"
  adaptive_icon_foreground: "assets/foreground-color.png"
  adaptive_icon_monochrome: "assets/foreground-bw.png"
  image_path_ios_tinted_grayscale: "assets/foreground-bw.png"
  windows:
    generate: true
    image_path: "assets/logo-color-desktop.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo-color-desktop.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/black-ultra-standing-front.webp
    - assets/black-lite-standing-front.webp
    - assets/logo.png
    - assets/black-ultra-standing-front-flashing.webp
    - assets/black-lite-standing-front-flashing.webp
    - assets/licenses/BSD-3-Clause.md
    - assets/licenses/GPL3.md
    - assets/licenses/LGPL3.md
    - assets/licenses/MIT.md

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf