name: enhanced_chameleon_ultra_gui
description: Enhanced cross-platform GUI for Chameleon Ultra with Proxmark3 Iceman firmware compatibility.
publish_to: "none"

version: 2.0.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies needed by main.dart
  provider: ^6.1.2
  
  # Internationalization (needed by main.dart)
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400