name: enhanced_chameleon_ultra_gui
description: Enhanced cross-platform GUI for Chameleon Ultra with Proxmark3 Iceman firmware compatibility.
publish_to: "none"

version: 2.0.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter dependencies
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.1.2
  path: ^1.8.3
  async: ^2.11.0
  convert: ^3.1.1
  collection: ^1.18.0
  crypto: ^3.0.3
  
  # File operations
  file_picker: ^8.0.0+1
  
  # UI components
  flutter_staggered_grid_view: ^0.7.0
  flutter_colorpicker: ^1.1.0
  
  # Terminal and code highlighting
  xterm: ^3.5.0
  flutter_highlight: ^0.7.0
  
  # Utilities
  uuid: ^4.2.1
  logger: ^2.0.2+1
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  
  # Permissions
  permission_handler: ^11.3.0
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # QR and scanning
  qr_flutter: ^4.1.0
  
  # Archive support
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400